version: 3;

services:
  backend:
    build: ./api
    container_name: "carrier"
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
