version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carrier
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/docs" ]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 10s

  db:
    image: mysql:8.0.29
    container_name: "mysql_carrier"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql/conf.d:/app/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    env_file: ./backend/.env
    environment:
      TZ: Asia/Seoul
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "$${MYSQL_DATABASE}",
          "-h",
          "localhost",
          "-uroot",
          "-p$${MYSQL_ROOT_PASSWORD}",
          "-e",
          "\"SHOW DATABASES;\""
        ]
      interval: 60s
      timeout: 10s
      retries: 10
